from config import normalize_zone_type
from neo4j import GraphDatabase


class Neo4jLoader:
    def __init__(
        self,
        uri: str,
        username: str,
        password: str,
        database: str = "neo4j",
    ):
        self.driver = GraphDatabase.driver(
            uri,
            auth=(username, password),
        )

        self.database = database

        self.driver.verify_connectivity()

    def load_cells(self, city_id: str):
        """Read one city from the graph generated by urban_city_dataset.

        The importer creates :GridCell nodes and :CONNECTED_TO links in `urban`.
        city_id is passed as a Cypher parameter rather than interpolated into SQL.
        """
        query = """
        MATCH (c:GridCell {city_id: $city_id})
        OPTIONAL MATCH (c)-[:CONNECTED_TO]-(n:GridCell {city_id: $city_id})

        RETURN
            c.cell_id AS id,
            c.population AS population,
            c.type AS type,
            c.green_cover_pct AS green_cover,
            c.elevation_m AS elevation,
            c.dist_to_boundary_m AS distance_to_boundary,
            collect(DISTINCT n.cell_id) AS neighbors
        ORDER BY c.cell_id
        """

        records, _, _ = self.driver.execute_query(
            query,
            {"city_id": city_id},
            database_=self.database,
        )

        cells = []
        for record in records:
            cell = record.data()
            cell["type"] = normalize_zone_type(cell["type"])
            cell["neighbors"] = [neighbor for neighbor in cell["neighbors"] if neighbor]
            cells.append(cell)
        if not cells:
            raise ValueError(
                f"No GridCell records found for city_id={city_id!r} in database {self.database!r}"
            )
        return cells

    def close(self):
        self.driver.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.close()
